### ISSUE TITLE
Melasta SLPBB042126HV missing data

### ISSUE THREAD

**Issue by EduartCelislamisc** [Oxford-Brookes-HVES/BTC#1]
Dear BTC consortium,
I am interested in the data you got from your tests on the Melasta SLPBB042126HV which are listed in the tests you did. I remember that some times ago they were available to be downloaded but now I can not find them anymore. Can you explain to me where I can find them? I am part of the Battery Pack division of the formula student team at Politecnico of Turin, and we would use these data to have a better understanding of our battery pack.
I will wait for your response,
Kind regards

**Comment by BradyPlanden** [comment]
Hello Eduart,

This repository provides an open-source example of the [BTC](https://hves.brookes.ac.uk/btc/), it will only include cells that have been designated to share. It is here to provide the community with an example of the data available from the BTC. If you'd like the data from the other cells tested including the `SLPBB042126HV`, please take a look at the discounted FS pricing in the above link.
